name: POC - Semgrep + SBOM (CycloneDX) + CBOM simples

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Semgrep com regras próprias (se existir) + auto-rules
      - name: Semgrep (rules + auto)
        uses: returntocorp/semgrep-action@v1
        with:
          args: >
            --config=auto
            --config semgrep-rules/crypto_rules.yml
            --json --output semgrep-results.json
        env:
          SEMGREP_RULES: p/default # opcional; usa regras públicas
          # Se você NÃO usar a plataforma Semgrep (app.semgrep.com), não precisa de token

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

  sbom:
    name: Generate SBOM (CycloneDX)
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Syft CycloneDX (json + xml)
        run: |
          docker run --rm -v "${{ github.workspace }}":/w -w /w anchore/syft:latest dir:. -o cyclonedx-json=sbom-cyclonedx.json
          docker run --rm -v "${{ github.workspace }}":/w -w /w anchore/syft:latest dir:. -o cyclonedx=sbom-cyclonedx.xml

      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            sbom-cyclonedx.json
            sbom-cyclonedx.xml

  cbom:
    name: Build simple CBOM (grep)
    runs-on: ubuntu-latest
    needs: sbom
    steps:
      - uses: actions/checkout@v4

      - name: Grep crypto indicators
        shell: bash
        run: |
          set -e
          grep -R --line-number -iE "MD5|SHA1|SHA-1|SHA256|AES|RSA|ECDSA|ECIES|PBKDF2|HKDF|Scrypt|bcrypt|PKCS1|PKCS8|ECB|CBC|GCM|curve25519|x25519|Kyber|Dilithium|SPHINCS" . > found_crypto_strings.txt || true
          cut -d: -f1 found_crypto_strings.txt | sort -u > files_with_crypto.txt || true
          awk -F: '{print NR","$0}' found_crypto_strings.txt > cbom_matches.csv || true

      - name: Upload CBOM candidates
        uses: actions/upload-artifact@v4
        with:
          name: cbom-candidates
          path: |
            found_crypto_strings.txt
            files_with_crypto.txt
            cbom_matches.csv
